spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git 地址
          username: 账号
          password: 密码
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
## 暴露bus refresh 接口
management:
  endpoints:
    web:
      exposure:
        include: "*"
