server:
  port: 9000
eureka:
  instance:
      hostname: localhost
      non-secure-port: ${server.port}   # 不指定当前属性会默认为8080 指端口无效
  #server:
      #enable-self-preservation: false   # 关闭自我保护（开发环境操作 ）
  client:
      registerWithEureka: false  # 自己是注册中心 不注册
      fetchRegistry: false # 自己是注册中心 不在查找
      serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/